//getting songs from db
export const LOADING_GET_SUBSCRIPTION_TYPES = 'LOADING_GET_SUBSCRIPTION_TYPES';
export const SUCCESS_GET_SUBSCRIPTION_TYPES = 'SUCCESS_GET_SUBSCRIPTION_TYPES';
export const FAILURE_GET_SUBSCRIPTION_TYPES = 'FAILURE_GET_SUBSCRIPTION_TYPES';


