//getting songs from db
export const LOADING_GET_USER_SUBSCRIPTION = 'LOADING_GET_USER_SUBSCRIPTION';
export const SUCCESS_GET_USER_SUBSCRIPTION = 'SUCCESS_GET_USER_SUBSCRIPTION';
export const FAILURE_GET_USER_SUBSCRIPTION = 'FAILURE_GET_USER_SUBSCRIPTION';


